### ISSUE TITLE
Docker hub description is yet python 3.5

### ISSUE THREAD

**Issue by wijae** [frol/docker-alpine-python3#10]
In [Docker Hub](https://hub.docker.com/r/frolvlad/alpine-python3), this image has description as below.

"The smallest Docker image with Python 3.5 (~61MB) "

If you are not busy, how about change it to "The smallest Docker image with Python 3.6 (~61MB)" as github description?

thanks.

**Comment by frol** [comment]
Thanks for the reminder! Done.

**Comment by luisdemarchi** [comment]
@frol Now the title says Python 3.6 and the description (and console) says Python 3.7. How can I get back to Python 3.6?

**Comment by frol** [comment]
@luisdemarchi there is no way to downgrade, sorry. I use an official `python3` package from Alpine Linux, which gets rolling updates.
