### ISSUE TITLE
pip install grpcio failed

### ISSUE THREAD

**Issue by LeiYangGH** [frol/docker-alpine-python3#14]
some error message:

>   creating python_build/lib.linux-x86_64-3.7/grpc/_cython/_credentials
>   copying src/python/grpcio/grpc/_cython/_credentials/roots.pem -> python_build/lib.linux-x86_64-3.7/grpc/_cython/_credentials
>   running build_ext
>   error: [Errno 2] No such file or directory: 'cc': 'cc'

**Comment by frol** [comment]
It seems that it needs C compiler to build this package. You will need to install gcc (`apk add --no-cache gcc`). It may also require some other dependencies like `musl-dev`, `python3-dev`.
