### ISSUE TITLE
pip install times out for some packages - can't find pattern

### ISSUE THREAD

**Issue by rbuckland** [frol/docker-alpine-python3#2]
I have a simple case of trying to install jinja2 .. or netifaces (needs python-dev also)

Example 1: 

```
vagrant@vagrant-ubuntu-trusty-64:~$ docker run --rm frolvlad/alpine-python3 pip install netifaces
Collecting netifaces
  Retrying (Retry(total=4, connect=None, read=None, redirect=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.python.org', port=443): Read timed out. (read timeout=15)",)': /simple/netifaces/
# the above should download, then fail as we don't have python-dev .. but it can't download it to start with
# times-out
```

Example 2 :
Times out after finding the jinja2 package, and tries to locate `MarkupSafe`

```
vagrant@vagrant-ubuntu-trusty-64:~$ docker run --rm frolvlad/alpine-python3 pip install jinja2
Collecting jinja2
  Downloading Jinja2-2.8-py2.py3-none-any.whl (263kB)
Collecting MarkupSafe (from jinja2)
  Retrying (Retry(total=4, connect=None, read=None, redirect=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.python.org', port=443): Read timed out. (read timeout=15)",)': /simple/markupsafe/
```

**Comment by rbuckland** [comment]
We resolved this as a link issue. All is good; no need to look into it.

**Comment by frol** [comment]
@rbuckland This sounds like either temporary pypi overload or your internet connection issue. There is nothing to do with my image. As to the `python-dev`, it is a build-dependency, so I suggest you write your Dockefile where you will install it, install your application dependencies and remove all build dependencies including `python-dev` in one `RUN` step.
