### ISSUE TITLE
How can I use pip/pip3 installed with Python3 to install other packages in CodeBuild?

### ISSUE THREAD

**Issue by panyi121** [frol/docker-alpine-python3#7]
I find your docker image neat to download a Python3.6 image to CodeBuild, I also need to use pip against Python3.6 to install other dependency libraries. Can you tell me how can I do that? 

I tried "python3 -m pip install -t 'lib' injector==0.12.1" but encountered error: cannot find pip module under python3. 

FYI, 
I am using docker image: aws/codebuild/docker:1.12.1 from http://docs.aws.amazon.com/codebuild/latest/userguide/build-env-ref-available.html, since the docker image above preinstalled pip. 

Thanks!

**Comment by frol** [comment]
Sorry, I don't understand what you mean. Running the command in my image finishes just fine:

```
$ docker run -it --rm frolvlad/alpine-python3 sh
/ # python3 -m pip install -t 'lib' injector==0.12.1
Collecting injector==0.12.1
  Downloading injector-0.12.1.tar.gz
Collecting setuptools>=0.6b1 (from injector==0.12.1)
  Downloading setuptools-36.6.0-py2.py3-none-any.whl (481kB)
    100% |████████████████████████████████| 481kB 1.7MB/s
Collecting typing (from injector==0.12.1)
  Downloading typing-3.6.2-py3-none-any.whl
Installing collected packages: setuptools, typing, injector
  Running setup.py install for injector ... done
Successfully installed injector-0.12.1 setuptools-36.6.0 typing-3.6.2
```
